services:
  test:
    image: bluenviron/mediamtx:latest-ffmpeg
    restart: always
    volumes:
      - ./test-stream.mediamtx.yml:/mediamtx.yml

  mux:
    image: bluenviron/mediamtx:latest-ffmpeg
    restart: always
    environment:
      - MTX_PROTOCOLS=tcp
    ports:
      - '8554:8554'
      - '1935:1935'
      - '8888:8888'
      - '8889:8889'
      - '8890:8890/udp'
      - '8189:8189/udp'
      - '9996:9996'
    volumes:
      - ./mux.dev.mediamtx.yml:/mediamtx.yml
      - recordings:/recordings

volumes:
  recordings:
