name: census-core-services
services:
  db:
    image: postgres:latest
    container_name: 'cc-db'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: db02
    ports:
      - '5432:5432'
    volumes:
      - ccccpgdata:/var/lib/postgresql
    command:
      - postgres
      - -c
      - wal_level=logical

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: 'azurite --loose --blobHost 0.0.0.0 --blobPort 10000 --location /workspace --debug /workspace/debug.log'
    container_name: 'cc-azurite'
    hostname: azurite
    restart: always
    ports:
      - '10000:10000'
    volumes:
      - ccazuritedata:/workspace
volumes:
  ccazuritedata:
  ccccpgdata:
