packages:
  - 'clips/manager'
  - 'clips/provider'
  - 'census/website'
  - 'census/api'
  - 'census/levels'
  - 'census/sync'
  - 'census/forms'
  - 'infrastructure/pulumi'
  - 'shared/*'

catalog:
  '@trpc/client': ^11.16.0
  '@trpc/server': ^11.16.0
