config:
  azure-native:location: northcentralus
  census:cf-account-id: 1f4b83a9106fec33c984912210d93e1b
  census:cf-zone-id: 23a2fcb1193af1cca6791f055394e334
  census:deployment-environment: staging
  census:api-subdomain: census-api-staging
  census:site-hostname: staging.census.alveussanctuary.org
  census:alveus-client-id: census-staging
  census:api-scale-behaviour: scale_to_zero
  # CI overrides these image values on deploy.
  census:image: ghcr.io/alveusgg/census/api:28527541716
  census:ipx: ghcr.io/alveusgg/census/ipx:latest
  # Set staging secrets with Pulumi before the first deployment:
  # - census:mux-token-secret
  # - census:alveus-client-secret
  # - census:s3-access-key-id
  # - census:s3-secret-access-key
  # - census:twitch-client-secret
  # - census:sentry-dsn
  census:mux-token-id: 2fba08c2-0da0-4898-bf9e-f0bc4dd7e4f0
  census:s3-bucket: census-staging-clip-storage
  census:s3-endpoint: https://1f4b83a9106fec33c984912210d93e1b.r2.cloudflarestorage.com
  census:s3-public-url: https://census-staging-storage.alveus.gg
  census:twitch-client-id: sjj3rcjojtqyeobptmjf3pjukaerkc
