version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: db01
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    command:
      - postgres
      - -c
      - wal_level=logical
volumes:
  dragonflydata:
  pgdata:
