name: CI

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_census_api:
    name: Build Census API
    uses: ./.github/workflows/build-census-api.yml

  build_census_ui:
    name: Build Census UI
    uses: ./.github/workflows/build-census-ui.yml

  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    needs:
      - build_census_api
      - build_census_ui
    permissions:
      id-token: write
      contents: read

    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: actions/download-artifact@v4
        with:
          name: ui-build
          path: census/website/ui

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - uses: pulumi/auth-actions@v1
        name: Login to Pulumi
        with:
          organization: alveusgg
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:changesbyjames

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: pulumi/actions@v6
        name: Deploy infrastructure
        id: pulumi
        continue-on-error: true
        with:
          command: up
          stack-name: alveusgg/prod
          work-dir: infrastructure/pulumi
          config-map: |
            {
              "image": { value: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main-${{ github.run_id }}-census-api", secret: false },
              "ipx": { value: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-ipx", secret: false }
            }
        env:
          ARM_USE_OIDC: true
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Build & upload worker
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          packageManager: pnpm
          wranglerVersion: '4.80.0'
          workingDirectory: census/website
          preCommands: |
            echo '${{ steps.pulumi.outputs.wranglerConfig }}' > wrangler.generated.jsonc
            printf '%s' '${{ steps.pulumi.outputs.workerSourceBase64 }}' | base64 --decode > worker.generated.js
          command: |
            deploy --config wrangler.generated.jsonc --env prod
