name: CI

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  CENSUS_API_IMAGE: ghcr.io/${{ github.repository }}/api
  IPX_IMAGE: ghcr.io/${{ github.repository }}/ipx
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build_census_api:
    name: Build Census API
    uses: ./.github/workflows/build-census-api.yml

  build_census_ui:
    name: Build Census UI
    uses: ./.github/workflows/build-census-ui.yml

  deploy_staging:
    name: Deploy to staging
    needs:
      - build_census_api
      - build_census_ui
    uses: ./.github/workflows/deploy-census.yml
    with:
      environment: staging
      environment_url: https://staging.census.alveussanctuary.org
      pulumi_stack: alveusgg/staging
      wrangler_env: staging
      sentry_environment: staging
    secrets: inherit

  deploy_production:
    name: Deploy to production
    needs:
      - deploy_staging
    uses: ./.github/workflows/deploy-census.yml
    with:
      environment: production
      environment_url: https://census.alveussanctuary.org
      pulumi_stack: alveusgg/prod
      wrangler_env: prod
      sentry_environment: production
    secrets: inherit
